export { default as Home } from './home/Home'
export { default as AboutMe } from './about/AboutMe'
export { default as Skills } from './skills/Skills'
export { default as Projects } from './projects/Projects'
export { default as Contact } from './contact/Contact'
export { default as Navbar } from './navbar/Navbar'
export { default as Footer } from './footer/Footer'
